package dev.hinaka.pokedex.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class PokedexColors(
    val typeNormal: Color,
    val onTypeNormal: Color,
    val typeFighting: Color,
    val onTypeFighting: Color,
    val typeFlying: Color,
    val onTypeFlying: Color,
    val typePoison: Color,
    val onTypePoison: Color,
    val typeGround: Color,
    val onTypeGround: Color,
    val typeRock: Color,
    val onTypeRock: Color,
    val typeBug: Color,
    val onTypeBug: Color,
    val typeGhost: Color,
    val onTypeGhost: Color,
    val typeSteel: Color,
    val onTypeSteel: Color,
    val typeFire: Color,
    val onTypeFire: Color,
    val typeWater: Color,
    val onTypeWater: Color,
    val typeGrass: Color,
    val onTypeGrass: Color,
    val typeElectric: Color,
    val onTypeElectric: Color,
    val typePsychic: Color,
    val onTypePsychic: Color,
    val typeIce: Color,
    val onTypeIce: Color,
    val typeDragon: Color,
    val onTypeDragon: Color,
    val typeDark: Color,
    val onTypeDark: Color,
    val typeFairy: Color,
    val onTypeFairy: Color,
    val typeUnknown: Color,
    val onTypeUnknown: Color,
)

val LocalPokedexColors = staticCompositionLocalOf {
    PokedexColors(
        typeNormal = Color.Unspecified,
        onTypeNormal = Color.Unspecified,
        typeFighting = Color.Unspecified,
        onTypeFighting = Color.Unspecified,
        typeFlying = Color.Unspecified,
        onTypeFlying = Color.Unspecified,
        typePoison = Color.Unspecified,
        onTypePoison = Color.Unspecified,
        typeGround = Color.Unspecified,
        onTypeGround = Color.Unspecified,
        typeRock = Color.Unspecified,
        onTypeRock = Color.Unspecified,
        typeBug = Color.Unspecified,
        onTypeBug = Color.Unspecified,
        typeGhost = Color.Unspecified,
        onTypeGhost = Color.Unspecified,
        typeSteel = Color.Unspecified,
        onTypeSteel = Color.Unspecified,
        typeFire = Color.Unspecified,
        onTypeFire = Color.Unspecified,
        typeWater = Color.Unspecified,
        onTypeWater = Color.Unspecified,
        typeGrass = Color.Unspecified,
        onTypeGrass = Color.Unspecified,
        typeElectric = Color.Unspecified,
        onTypeElectric = Color.Unspecified,
        typePsychic = Color.Unspecified,
        onTypePsychic = Color.Unspecified,
        typeIce = Color.Unspecified,
        onTypeIce = Color.Unspecified,
        typeDragon = Color.Unspecified,
        onTypeDragon = Color.Unspecified,
        typeDark = Color.Unspecified,
        onTypeDark = Color.Unspecified,
        typeFairy = Color.Unspecified,
        onTypeFairy = Color.Unspecified,
        typeUnknown = Color.Unspecified,
        onTypeUnknown = Color.Unspecified,
    )
}